key: value
#磁力链下载设置
username: admin
passwd: 123456
server: http://192.168.1.75:8080

#mqtt配置项
mqtt_server_host: your_mqtt_server.domain
mqtt_server_port: 1883
clientId: your_client_id
mqtt_username: your_username
mqtt_passwd: your_password
mqtt_reconnectPeriod: 1000

#卡路里识别
API_Key: your_api_key
Secret_Key: your_secret_key
